### PR TITLE
Fixing MoleculeGraph

### PR DESCRIPTION
**Pull request by WardLT**
I am looking to use MEGNet in one of my projects, and found the MoleculeGraph class seems to be incomplete.

I have started changing the code for MoleculeGraph to match up with what I think you are going for. 

This PR isn't complete, but I figured to open a draft so that we could have a conversation about whether I am on the right path. 

Things that I'm already aware I need to do (please edit if you see more):

- [x] Write unit tests for this code
- [x] Create/modify existing examples to use new MoleculeGraph
- [x] Fix all TODOs marked in the code

### CODE REVIEW

**Comment by chc273** [comment]
@WardLT Thanks for your valuable inputs! We will go through carefully. We agree that the molecule part is not being actively worked on and we would love to include contributions from the community. Your inputs will be especially valuable. 

Part of the reason for the problems with qm9.py is that we generally do not prefer manual features. Currently for the megnet pretrained models, we only shared the one using only "atom type" (integer) as atom attributes and "bond length" as the bond attributes. We will follow up with your suggestions and hopefully we will make the molecule part much better for use together.

**Comment by WardLT** [comment]
Sounds great, @chc273 ! I'll continue working on making it easier to use megnet with molecular data. 

To give you some context, which you might have already guessed, my goal is to be able to efficiently use megnet with molecule data that is not from the pre-processed version of QM9 available with megnet. 

FYI: My time to work on this is going to be fractured, so commits are going to be sporadic.

**Comment by shyuep** [comment]
@WardLT Just wanted to thank you for making the effort. Don't worry if the commits are sporadic. On our side, we are more focused on the crystal models for the moment. 

When you are done, we are happy to add an acknowledgement on your contributions.

**Comment by WardLT** [comment]
Alright, this is ready for review now. 

There are a few places where I made changes that could use closer review:

- I made the `pybel` and `rdkit` imports in `molecule.py` mandatory, as they are used extensively. Would you prefer I issue a warning if they are not installed?
- I added optimal dependencies for molecules in `setup.py`

**Comment by shyuep** [comment]
Many thanks. I would definitely make pybel and rdkit optional, given that these are not trivial to install and not everyone works on molecule models. Based on the current code, it does seem to be fine since the tests are skipped if the imports fail and even if someone does not have pybel or rdkit installed, the crystal models seem to work fine. 

@chc273 Can you review all the changes and merge if ok? Thanks.

**Comment by chc273** [comment]
@WardLT This looks great! 
I will be looking into details soon. The `pybel` by default from `pip` is not the one we need. The correct one is from `openbabel` and so far only installation from conda or from source worked. 

@shyuep  I will be working on it today.

**Comment by chc273** [comment]
@WardLT Following @shyuep 's comment, 
Now we have a wrapper called `MEGNetMolecule` for pymatgen `Molecule` located in `megnet.utils.molecule`, basically if you convert pymatgen Molecule to `MEGNetMolecule` by a simple class method call, you can use all the other codes and models for crystals on molecules. 

In principle, people can work with molecules using this strategy without the need to install `openbabel` or `rdkit`. I would agree that `openbabel (pybel)` and `rdkit` are optional for megnet. 

Thanks for all the inputs.

**Comment by WardLT** [comment]
I changed the requirement to openbabel from pybel, and made those not required to use SimpleMolGraph since that relies on using MegNetMolecule and not pybel.

**Comment by chc273** [comment]
@WardLT  Great job! 

I tried to run the example `molecule_example.ipynb` and got many warning messages like the following
`Explicit valence for atom # 3 N, 4, is greater than permitted` 

When doing the prediction, warnings like the following showed up 
`Can't kekulize mol.  Unkekulized atoms: 2 7 8` 

However, overall the model is training and predicting as expected. 

Could you comment on those warnings? 
Thanks

**Comment by WardLT** [comment]
I am not sure about those warnings :\ 

openbabel produced a lot of warnings for me when using it in some other contexts, and I'm not yet sure on how seriously to take them.

My plan in the next few days is to train MEGNet with QM9 and inputs generated with MoleculeGraph partly as a test to see if the feature generation code work. I'll let you know how that pans out

**Comment by chc273** [comment]
Sounds great. I am looking forward to it.

**Pull request merged**
